[package]
name = "discordlib"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2.32"
reqwest = { version = "0.12", features = ["json"] }
tokio = {version = "1.39.2", features = ["full"]}
tokio-tungstenite = {version = "0.23.1", features = ["native-tls"]}
